/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.controladores.DetalleEmpleadoController;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.modelos.entidades.DetalleEmpleado;

/**
 *
 * @author Elena
 */
public class JDialogDetalleEmpleado extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogDetalleEmpleado.class.getName());
    private DetalleEmpleadoController controller;
    private Integer idEmpleado;

    /**
     * Creates new form JDialogDetalleEmpleado
     */
    public JDialogDetalleEmpleado(java.awt.Frame parent, boolean modal, Integer idEmpleado) {
        super(parent, modal);
        initComponents();
        this.idEmpleado = idEmpleado;

        this.setTitle("Detalles del Empleado");
        this.setSize(925, 600);
        this.setResizable(false);
        setLocationRelativeTo(null);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("parqueAtracciones");
        this.controller = new DetalleEmpleadoController(emf);

        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecargar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdDetalle = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        txtObservaciones = new javax.swing.JTextField();
        txtIdParque = new javax.swing.JComboBox<>();
        txtIdEmpleado = new javax.swing.JComboBox<>();

        btnRecargar1.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnRecargar1.setText("Recargar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Detalles del Empleado");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Detalle", "ID Empleado", "ID Parque", "Fecha Inicio", "Fecha Fin", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnInsertar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnRecargar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnBuscar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel2.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel2.setText("ID Detalle:");

        jLabel3.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel3.setText("Empleado:");

        jLabel4.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel4.setText("Parque:");

        jLabel5.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel5.setText("Fecha Inicio:");

        jLabel6.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel6.setText("Fecha Fin: ");

        jLabel7.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel7.setText("Observaciones:");

        txtIdDetalle.addActionListener(this::txtIdDetalleActionPerformed);

        txtFechaInicio.addActionListener(this::txtFechaInicioActionPerformed);

        txtFechaFin.addActionListener(this::txtFechaFinActionPerformed);

        txtObservaciones.addActionListener(this::txtObservacionesActionPerformed);

        txtIdParque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona Parque --", "Parque Aventura", "Diversion Park", "Magic World", "FunLand", "AquaPark" }));

        txtIdEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona empleado --", "Luis Martinez Lopez", "Sara Perez Diaz", "Carlos Ruiz Gil", "Ana Sanchez Lopez", "Pedro Navarro Rey" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(104, 104, 104)
                .addComponent(btnCancelar)
                .addGap(321, 321, 321))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(btnInsertar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnActualizar)
                                                .addGap(154, 154, 154)
                                                .addComponent(btnBorrar))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(113, 113, 113)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtIdDetalle)
                                                    .addComponent(txtIdParque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtIdEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnLimpiar)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel7)))
                                        .addGap(12, 12, 12)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(btnRecargar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnInsertar)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtIdDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRecargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnBuscar))
                .addGap(149, 149, 149))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un detalle del empleado.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el detalle del empleado?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            controller.delete(id);

            cargarTabla();

            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Detalle del empleado contratado eliminado.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar el detalle del empleado.\n" + "Tiene registros relacionados.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una contratación de un servicio.");
            return;
        }
        if (!txtIdDetalle.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Recuerda que el ID del detalle no se puede actualizar.");
            return;
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            DetalleEmpleado d = controller.findById(id);

            String codEmpleado = "";
            int selEmpleado = txtIdEmpleado.getSelectedIndex();
            int selParque = txtIdParque.getSelectedIndex();
            String idParque = selParque > 0 ? String.valueOf(selParque) : "";
            String fechaInicio = txtFechaInicio.getText().trim();
            String fechaFin = txtFechaFin.getText().trim();
            String observaciones = txtObservaciones.getText().trim();

            // VALIDACIONES
            if (fechaInicio.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes de introducir una fecha de inicio.");
                return;
            }

            if (selEmpleado == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un empleado.");
                return;
            }
            if (selParque == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un parque.");
                return;
            }

            // FECHA
            Date inicio = validarFecha(fechaInicio);
            if (inicio == null) {
                return;
            }

            Date fin = null;

            if (!fechaFin.isBlank()) {

                fin = validarFecha(fechaFin);

                if (fin == null) {
                    return;
                }
            }

            if (fin != null && fin.before(inicio)) {
                JOptionPane.showMessageDialog(this, "La fecha de fin no puede ser anterior a la fecha de inicio.");
                return;
            }

            // ACTUALIZAR DATOS
            d.setCodEmpleado(selEmpleado);
            d.setCodParque(selParque);
            d.setFechaInicio(inicio);
            d.setFechaFin(fin);
            d.setObservaciones(observaciones);

            controller.update(d);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Detalles del empleado actualizada correctamente.");

            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtIdDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDetalleActionPerformed

    private void txtFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaInicioActionPerformed

    private void txtFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFinActionPerformed

    private void txtObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            txtIdDetalle.setText(jTable1.getValueAt(fila, 0).toString());
            try {
                int idEmpleadoVal = Integer.parseInt(jTable1.getValueAt(fila, 1).toString());
                txtIdEmpleado.setSelectedIndex(idEmpleadoVal);
            } catch (Exception ex) {
                txtIdEmpleado.setSelectedIndex(0);
            }
            try {
                int idParqueVal = Integer.parseInt(jTable1.getValueAt(fila, 2).toString());
                txtIdParque.setSelectedIndex(idParqueVal);
            } catch (Exception ex) {
                txtIdParque.setSelectedIndex(0);
            }
            txtFechaInicio.setText(jTable1.getValueAt(fila, 3).toString());
            txtFechaFin.setText(jTable1.getValueAt(fila, 4).toString());
            txtObservaciones.setText(jTable1.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        cargarTabla();

        limpiarCampos();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {

            DetalleEmpleado d = new DetalleEmpleado();

            int selEmpleado = txtIdEmpleado.getSelectedIndex();
            int selParque = txtIdParque.getSelectedIndex();
            String codParque = selParque > 0 ? String.valueOf(selParque) : "";
            String fechaInicio = txtFechaInicio.getText().trim();
            String fechaFin = txtFechaFin.getText().trim();
            String observaciones = txtObservaciones.getText().trim();

            // VALIDACIONES
            if (selEmpleado == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un empleado.");
                return;
            }
            if (selParque == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un parque.");
                return;
            }
            if (fechaInicio.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debes de introducir una fecha de inicio.");
                return;
            }
            if (!txtIdDetalle.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID del detalle no se puede insertar.");
                return;
            }

            // FECHA
            Date inicio = validarFecha(fechaInicio);

            if (inicio == null) {
                return;
            }

            Date fin = null;

            if (!fechaFin.isBlank()) {

                fin = validarFecha(fechaFin);

                if (fin == null) {
                    return;
                }
            }

            // ACTUALIZAR DATOS
            d.setCodEmpleado(selEmpleado);
            d.setCodParque(selParque);
            d.setFechaInicio(inicio);
            d.setFechaFin(fin);
            d.setObservaciones(observaciones);

            controller.create(d);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Entrada insertada correctamente.");

            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        // LIMPIAR TABLA
        modelo.setRowCount(0);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        // CAMPOS FILTRO
        String idDetalle = txtIdDetalle.getText().trim();
        int selEmpleado = txtIdEmpleado.getSelectedIndex();
        String codEmpleado = selEmpleado > 0 ? String.valueOf(selEmpleado) : "";
        int selParque = txtIdParque.getSelectedIndex();
        String codParque = selParque > 0 ? String.valueOf(selParque) : "";
        String fechaInicio = txtFechaInicio.getText().trim();
        String fechaFin = txtFechaFin.getText().trim();
        String observaciones = txtObservaciones.getText().trim();

        List<DetalleEmpleado> lista = controller.findAll();

        boolean encontrado = false;

        for (DetalleEmpleado d : lista) {

            boolean coincide = true;

            // ID DETALLE
            if (!idDetalle.isEmpty()) {
                String id = String.valueOf(d.getCodDetalle());

                if (!id.contains(idDetalle)) {
                    coincide = false;
                }
            }

            // COD EMPLEADO
            if (!codEmpleado.isEmpty()) {
                String empleado = String.valueOf(d.getCodEmpleado());

                if (!empleado.contains(codEmpleado)) {
                    coincide = false;
                }
            }

            // COD PARQUE
            if (!codParque.isEmpty()) {
                String empleado = String.valueOf(d.getCodParque());

                if (!empleado.contains(codParque)) {
                    coincide = false;
                }
            }

            // FECHA INICIO: aceptar formato dd/MM/yyyy
            if (!fechaInicio.isEmpty()) {
                boolean matchInicio = false;

                try {
                    java.util.Date buscInicio = sdf.parse(fechaInicio);
                    String buscInicioFmt = sdf.format(buscInicio);
                    String fechaEmp = d.getFechaInicio() != null ? sdf.format(d.getFechaInicio()) : "";

                    if (fechaEmp.equals(buscInicioFmt)) {
                        matchInicio = true;
                    }
                } catch (Exception ex) {
                    String fechaEmp = d.getFechaInicio() != null ? sdf.format(d.getFechaInicio()).toLowerCase() : "";
                    if (fechaEmp.contains(fechaInicio.toLowerCase())) {
                        matchInicio = true;
                    }
                }

                if (!matchInicio) {
                    coincide = false;
                }
            }

            // FECHA FIN: aceptar formato dd/MM/yyyy
            if (!fechaFin.isEmpty()) {
                boolean matchFin = false;

                try {
                    java.util.Date buscFin = sdf.parse(fechaFin);
                    String buscFinFmt = sdf.format(buscFin);
                    String fechaF = d.getFechaFin() != null ? sdf.format(d.getFechaFin()) : "";

                    if (fechaF.equals(buscFinFmt)) {
                        matchFin = true;
                    }
                } catch (Exception ex) {
                    String fechaF = d.getFechaFin() != null ? sdf.format(d.getFechaFin()).toLowerCase() : "";
                    if (fechaF.contains(fechaFin.toLowerCase())) {
                        matchFin = true;
                    }
                }

                if (!matchFin) {
                    coincide = false;
                }
            }

            // OBSERVACIONES
            if (!observaciones.isEmpty()) {

                String obs = "";

                if (d.getObservaciones() != null) {
                    obs = d.getObservaciones().toLowerCase();
                }

                if (!obs.contains(observaciones)) {
                    coincide = false;
                }
            }

            // SI COINCIDE
            if (coincide) {

                modelo.addRow(new Object[]{
                    d.getCodDetalle(),
                    d.getCodEmpleado(),
                    d.getCodParque(),
                    sdf.format(d.getFechaInicio()),
                    sdf.format(d.getFechaFin()),
                    d.getObservaciones()
                });

                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void limpiarCampos() {
        txtIdDetalle.setText("");
        txtIdEmpleado.setSelectedIndex(0);
        txtIdParque.setSelectedIndex(0);
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
        txtObservaciones.setText("");
        jTable1.clearSelection();
    }

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<DetalleEmpleado> lista = controller.findByCodEmpleado(idEmpleado);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (DetalleEmpleado d : lista) {

            String fechaInicio = "";
            String fechaFin = "";

            if (d.getFechaInicio() != null) {
                fechaInicio = sdf.format(d.getFechaInicio());
            }

            if (d.getFechaFin() != null) {
                fechaFin = sdf.format(d.getFechaFin());
            }

            modelo.addRow(new Object[]{
                d.getCodDetalle(),
                d.getCodEmpleado(),
                d.getCodParque(),
                fechaInicio,
                fechaFin,
                d.getObservaciones()
            });
        }
    }

    private Date validarFecha(String textoFecha) {

        try {

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);

            return sdf.parse(textoFecha);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fecha incorrecta.\nFormato requerido: dd/MM/yyyy\nEjemplo: 04/06/2026");
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogDetalleEmpleado dialog = new JDialogDetalleEmpleado(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton btnRecargar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtIdDetalle;
    private javax.swing.JComboBox<String> txtIdEmpleado;
    private javax.swing.JComboBox<String> txtIdParque;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
