/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.controladores.DetalleServiciosController;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.modelos.entidades.DetalleServicios;

/**
 *
 * @author Elena
 */
public class JDialogDetalleServicios extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogDetalleServicios.class.getName());
    private DetalleServiciosController controller;
    private Integer idServicio;

    /**
     * Creates new form JDialogDetalleServicios
     */
    public JDialogDetalleServicios(java.awt.Frame parent, boolean modal, Integer idServicio) {
        super(parent, modal);
        initComponents();
        this.idServicio = idServicio;
        this.setTitle("Contratación de Servicios");
        this.setSize(925, 600);
        this.setResizable(false);
        setLocationRelativeTo(null);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("parqueAtracciones");
        this.controller = new DetalleServiciosController(emf);

        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsertar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdDetalle = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        txtIdCliente = new javax.swing.JComboBox<>();
        txtIdServicio = new javax.swing.JComboBox<>();

        btnInsertar1.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnInsertar1.setText("Insertar");

        jLabel5.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel5.setText("ID Servicio:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Contratación de Servicios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Detalle", "ID Cliente", "ID Servicio", "Cantidad", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnCancelar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnBuscar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnInsertar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");

        btnRecargar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        jLabel2.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel2.setText("ID Detalle:");

        jLabel3.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel3.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel4.setText("Servicio:");

        jLabel6.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel6.setText("Cantidad:");

        jLabel7.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel7.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        txtIdCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona empleado --","Juan Perez Lopez", "Ana Gomez Ruiz", "Luis Diaz Soto", "Maria Lopez Gil", "Carlos Navarro Rey" }));

        txtIdServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona servicio --", "Comida", "Taquilla", "Animacion", "Fotografia", "VIP" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecargar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdServicio, 0, 148, Short.MAX_VALUE)
                            .addComponent(txtIdCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdDetalle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar)
                            .addComponent(jLabel7))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnBuscar)
                            .addGap(135, 135, 135)
                            .addComponent(btnCancelar)
                            .addGap(289, 289, 289))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(232, 232, 232))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnInsertar)
                            .addGap(407, 407, 407)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertar)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRecargar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnBuscar))
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            txtIdDetalle.setText(jTable1.getValueAt(fila, 0).toString());
            try {
                int idClienteVal = Integer.parseInt(jTable1.getValueAt(fila, 1).toString());
                txtIdCliente.setSelectedIndex(idClienteVal);
            } catch (Exception ex) {
                txtIdCliente.setSelectedIndex(0);
            }
            try {
                int idServicioVal = Integer.parseInt(jTable1.getValueAt(fila, 2).toString());
                txtIdServicio.setSelectedIndex(idServicioVal);
            } catch (Exception ex) {
                txtIdServicio.setSelectedIndex(0);
            }
            txtCantidad.setText(jTable1.getValueAt(fila, 3).toString());
            txtObservaciones.setText(jTable1.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        cargarTabla();

        limpiarCampos();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un servicio contratado.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el servicio contratado?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            controller.delete(id);

            cargarTabla();

            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Servicio contratado eliminado.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar el servicio contratado.\n" + "Tiene registros relacionados.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una contratación de un servicio.");
            return;
        }

        try {
            int selCliente = txtIdCliente.getSelectedIndex();
            int selServicio = txtIdServicio.getSelectedIndex();

            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            DetalleServicios d = controller.findById(id);

            String cantidad = txtCantidad.getText().trim();
            String observaciones = txtObservaciones.getText().trim();

            // VALIDACIONES
            if (cantidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            if (selCliente == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente.");
                return;
            }
            if (selServicio == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio.");
                return;
            }
            if (!txtIdDetalle.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID del detalle no se puede actualizar.");
                return;
            }


            // ACTUALIZAR DATOS
            d.setCodCliente(selCliente);
            d.setCodServicio(selServicio);
            d.setCantidad(Integer.parseInt(cantidad));
            d.setObservaciones(observaciones);

            controller.update(d);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Contratación del servicio actualizada correctamente.");

            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            int selCliente = txtIdCliente.getSelectedIndex();
            int selServicio = txtIdServicio.getSelectedIndex();

            DetalleServicios d = new DetalleServicios();

            String cantidad = txtCantidad.getText().trim();
            String observaciones = txtObservaciones.getText().trim();

            // VALIDACIONES
            if (cantidad.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            if (selCliente == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente.");
                return;
            }
            if (selServicio == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un servicio.");
                return;
            }
            if (!txtIdDetalle.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID del detalle no se puede insertar.");
                return;
            }

            // SET DATOS
            d.setCodCliente(selCliente);
            d.setCodServicio(selServicio);
            d.setCantidad(Integer.parseInt(cantidad));
            d.setObservaciones(observaciones);

            controller.create(d);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Contratación del servicio insertada correctamente.");

            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        // LIMPIAR TABLA
        modelo.setRowCount(0);

        // CAMPOS FILTRO
        String idDetalle = txtIdDetalle.getText().trim();
        int selCliente = txtIdCliente.getSelectedIndex();
        String idCliente = selCliente > 0 ? String.valueOf(selCliente) : "";
        int selServicio = txtIdServicio.getSelectedIndex();
        String codServicio = selServicio > 0 ? String.valueOf(selServicio) : "";
        String cantidad = txtCantidad.getText().trim();
        String observaciones = txtObservaciones.getText().trim().toLowerCase();

        List<DetalleServicios> lista = controller.findAll();

        boolean encontrado = false;

        for (DetalleServicios d : lista) {

            boolean coincide = true;

            // ID DETALLE
            if (!idDetalle.isEmpty()) {
                String id = String.valueOf(d.getCodDetalleServicio());
                if (!id.contains(idDetalle)) {
                    coincide = false;
                }
            }

            // COD CLIENTE
            if (!idCliente.isEmpty()) {
                String cliente = String.valueOf(d.getCodCliente());
                if (!cliente.contains(idCliente)) {
                    coincide = false;
                }
            }

            // COD SERVICIO
            if (!codServicio.isEmpty()) {
                String servicio = String.valueOf(d.getCodServicio());
                if (!servicio.contains(codServicio)) {
                    coincide = false;
                }
            }

            // CANTIDAD
            if (!cantidad.isEmpty()) {
                String cant = String.valueOf(d.getCantidad());
                if (!cant.contains(cantidad)) {
                    coincide = false;
                }
            }

            // OBSERVACIONES
            if (!observaciones.isEmpty()) {

                String obs = "";

                if (d.getObservaciones() != null) {
                    obs = d.getObservaciones().toLowerCase();
                }

                if (!obs.contains(observaciones)) {
                    coincide = false;
                }
            }

            // SI COINCIDE
            if (coincide) {

                modelo.addRow(new Object[]{
                    d.getCodDetalleServicio(),
                    d.getCodCliente(),
                    d.getCodServicio(),
                    d.getCantidad(),
                    d.getObservaciones()
                });

                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<DetalleServicios> lista = controller.findByCodServicio(idServicio);

        for (DetalleServicios d : lista) {
            modelo.addRow(new Object[]{
                d.getCodDetalleServicio(),
                d.getCodCliente(),
                d.getCodServicio(),
                d.getCantidad(),
                d.getObservaciones()
            });
        }
    }

    private void limpiarCampos() {
        txtIdDetalle.setText("");
        txtIdCliente.setSelectedIndex(0);
        txtIdServicio.setSelectedIndex(0);
        txtCantidad.setText("");
        txtObservaciones.setText("");
        jTable1.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogDetalleServicios dialog = new JDialogDetalleServicios(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnInsertar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JComboBox<String> txtIdCliente;
    private javax.swing.JTextField txtIdDetalle;
    private javax.swing.JComboBox<String> txtIdServicio;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
