/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.controladores.EntradasController;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.modelos.entidades.Entradas;

/**
 *
 * @author Elena
 */
public class JDialogEntradas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEntradas.class.getName());
    private EntradasController controller;

    /**
     * Creates new form JDialogEntradas
     */
    public JDialogEntradas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Gestión Entradas");
        this.setSize(925, 600);
        this.setResizable(false);
        setLocationRelativeTo(null);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("parqueAtracciones");
        this.controller = new EntradasController(emf);

        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdEntrada = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtTipoEntrada = new javax.swing.JComboBox<>();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtIdParque = new javax.swing.JComboBox<>();
        txtIdCliente = new javax.swing.JComboBox<>();

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jButton2.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        jButton2.setText("Insertar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Gestión Entradas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Tipo Entrada", "ID Parque", "ID Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel3.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel4.setText("Tipo Entrada: ");

        jLabel5.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel5.setText("Parque:");

        jLabel6.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel6.setText("Cliente:");

        txtIdEntrada.addActionListener(this::txtIdEntradaActionPerformed);

        txtFecha.addActionListener(this::txtFechaActionPerformed);

        txtTipoEntrada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"-Tipo Entrada-", "individual", "grupal", "cumpleaños"}));
        txtTipoEntrada.addActionListener(this::txtTipoEntradaActionPerformed);

        btnInsertar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnRecargar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        btnBuscar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        txtIdParque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona Parque --", "Parque Aventura", "Diversion Park", "Magic World", "FunLand", "AquaPark" }));

        txtIdCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona cliente --", "Juan Perez Lopez", "Ana Gomez Ruiz", "Luis Diaz Soto", "Maria Lopez Gil", "Carlos Navarro Rey" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(txtIdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jLabel5))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(txtTipoEntrada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addGap(101, 101, 101)
                                                            .addComponent(jLabel6)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtIdParque, 0, 111, Short.MAX_VALUE)
                                                        .addComponent(txtIdCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(271, 271, 271)
                                            .addComponent(btnBorrar)
                                            .addGap(157, 157, 157)
                                            .addComponent(btnLimpiar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                                    .addComponent(btnActualizar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRecargar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(btnInsertar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnBuscar)
                        .addGap(151, 151, 151)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtIdEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtTipoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRecargar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCancelar))
                .addGap(141, 141, 141))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEntradaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una entrada.");
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            Entradas e = controller.findById(id);

            String fechaTexto = txtFecha.getText().trim();

            // COMBOBOX
            String tipoEntrada = txtTipoEntrada.getSelectedItem().toString();
            int selParque = txtIdParque.getSelectedIndex();
            int selCliente = txtIdCliente.getSelectedIndex();

            // VALIDACIONES
            if (fechaTexto.isEmpty() || selParque == 0 || selCliente == 0 || tipoEntrada.equals("-Tipo Entrada-")) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            
            if (selParque == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un parque.");
                return;
            }
            if (selCliente == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente.");
                return;
            }
            if (!txtIdEntrada.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID de la entrada no se puede actualizar.");
                return;
            }      

            // FECHA
            Date fecha = validarFecha(fechaTexto);

            // ACTUALIZAR DATOS
            e.setFecha(fecha);
            e.setTipoEntrada(tipoEntrada);
            e.setCodParque(selParque);
            e.setCodCliente(selCliente);

            controller.update(e);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Entrada actualizada correctamente.");

            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTipoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoEntradaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        cargarTabla();
        
        limpiarCampos();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una entrada.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar la entrada?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            controller.delete(id);

            cargarTabla();

            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Entrada eliminada.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar la entrada.\n" + "Tiene registros relacionados.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            Entradas e = new Entradas();

            String fechaTexto = txtFecha.getText().trim();

            // COMBOBOX
            String tipoEntrada = txtTipoEntrada.getSelectedItem().toString();
            int selParque = txtIdParque.getSelectedIndex();
            int selCliente = txtIdCliente.getSelectedIndex();

            // VALIDACIONES
            if (selParque == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un parque.");
                return;
            }
            if (selCliente == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente.");
                return;
            }
            if (fechaTexto.isEmpty() || tipoEntrada.equals("-Tipo Entrada-")) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            if (!txtIdEntrada.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID de la entrada no se puede insertar.");
                return;
            }

            // FECHA
            Date fecha = validarFecha(fechaTexto);

            // SET DATOS
            e.setFecha(fecha);
            e.setTipoEntrada(tipoEntrada);
            e.setCodParque(selParque);
            e.setCodCliente(selCliente);

            controller.create(e);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Entrada insertada correctamente.");

            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            txtIdEntrada.setText(jTable1.getValueAt(fila, 0).toString());
            txtFecha.setText(jTable1.getValueAt(fila, 1).toString());

            // COMBOBOX TIPO ENTRADA
            txtTipoEntrada.setSelectedItem(jTable1.getValueAt(fila, 2).toString());

            try {
                int idParqueVal = Integer.parseInt(jTable1.getValueAt(fila, 3).toString());
                txtIdParque.setSelectedIndex(idParqueVal);
            } catch (Exception ex) {
                txtIdParque.setSelectedIndex(0);
            }

            try {
                int idClienteVal = Integer.parseInt(jTable1.getValueAt(fila, 4).toString());
                txtIdCliente.setSelectedIndex(idClienteVal);
            } catch (Exception ex) {
                txtIdCliente.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        String idTexto = txtIdEntrada.getText().trim();
        String fecha = txtFecha.getText().trim().toLowerCase();
        String tipo = txtTipoEntrada.getSelectedItem().toString().toLowerCase();
        int selCliente = txtIdCliente.getSelectedIndex();
        String codCliente = selCliente > 0 ? String.valueOf(selCliente) : "";
        int selParque = txtIdParque.getSelectedIndex();
        String codParque = selParque > 0 ? String.valueOf(selParque) : "";

        List<Entradas> lista = controller.findAll();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        boolean encontrado = false;

        for (Entradas e : lista) {

            boolean coincide = true;

            if (!idTexto.isEmpty()) {

                String idEntrada = String.valueOf(e.getCodEntrada());

                if (!idEntrada.contains(idTexto)) {
                    coincide = false;
                }
            }

            validarFecha(fecha);
            String fechaFormateada = sdf.format(fecha);

            if (!fecha.isEmpty() && !fechaFormateada.contains(fecha)) {
                coincide = false;
            }

            if (!tipo.equals("-tipo entrada-")
                    && !e.getTipoEntrada().toLowerCase().contains(tipo)) {

                coincide = false;
            }

            if (!codCliente.isEmpty()) {

                String cliente = String.valueOf(e.getCodCliente());

                if (!cliente.contains(codCliente)) {
                    coincide = false;
                }
            }

            if (!codParque.isEmpty()) {

                String parque = String.valueOf(e.getCodParque());

                if (!parque.contains(codParque)) {
                    coincide = false;
                }
            }

            if (coincide) {

                modelo.addRow(new Object[]{
                    e.getCodEntrada(),
                    sdf.format(e.getFecha()),
                    e.getTipoEntrada(),
                    e.getCodParque(),
                    e.getCodCliente()
                });

                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<Entradas> lista = controller.findAll();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Entradas e : lista) {

            modelo.addRow(new Object[]{
                e.getCodEntrada(),
                sdf.format(e.getFecha()),
                e.getTipoEntrada(),
                e.getCodParque(),
                e.getCodCliente()
            });
        }
    }

    private void limpiarCampos() {
        txtIdEntrada.setText("");
        txtFecha.setText("");
        txtTipoEntrada.setSelectedIndex(0);
        txtIdParque.setSelectedIndex(0);
        txtIdCliente.setSelectedIndex(0);
        jTable1.clearSelection();
    }
    
    private Date validarFecha(String textoFecha) {

        try {

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);

            return sdf.parse(textoFecha);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fecha incorrecta.\nFormato requerido: dd/MM/yyyy\nEjemplo: 04/06/2026");
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEntradas dialog = new JDialogEntradas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JComboBox<String> txtIdCliente;
    private javax.swing.JTextField txtIdEntrada;
    private javax.swing.JComboBox<String> txtIdParque;
    private javax.swing.JComboBox<String> txtTipoEntrada;
    // End of variables declaration//GEN-END:variables
}
