/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.controladores.AtraccionesController;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.modelos.entidades.Atracciones;

/**
 *
 * @author Elena
 */
public class JDialogAtracciones extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAtracciones.class.getName());
    private Integer idZona;
    private Integer idParque;
    private AtraccionesController controller;

    /**
     * Creates new form JDialogAtracciones
     */
    public JDialogAtracciones(java.awt.Frame parent, boolean modal, Integer idZona, Integer idParque) {
        super(parent, modal);
        initComponents();
        this.idZona = idZona;
        this.idParque = idParque;
        this.setTitle("Gestión Atracciones");
        this.setSize(925, 600);
        this.setResizable(false);
        setLocationRelativeTo(null);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("parqueAtracciones");
        this.controller = new AtraccionesController(emf);

        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIdAtraccion = new javax.swing.JTextField();
        txtFechaInstalacion = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCapacidadMaxima = new javax.swing.JTextField();
        txtEdadMinima = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIdParque = new javax.swing.JComboBox<>();
        txtIdZona = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Gestión Atracciones");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha Instalación", "Descripción", "Capacidad Max.", "Edad Mínima", "ID Zona", "ID Parque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnInsertar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnRecargar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        btnBuscar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("David Libre", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel2.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel4.setText("Fecha Instalación:");

        jLabel5.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel5.setText("Descripción:");

        jLabel6.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel6.setText("Capacidad Máxima:");

        jLabel7.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel7.setText("Edad Mínima:");

        jLabel8.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel8.setText("Zona:");

        jLabel9.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel9.setText("Parque:");

        txtIdParque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona parque --", "Parque Aventura", "Diversion Park", "Magic World", "FunLand", "AquaPark" }));

        txtIdZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona zona --", "Infantil", "Acuatica", "Extrema", "Familiar", "Relax" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(btnActualizar)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnRecargar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnBorrar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnLimpiar))
                                            .addComponent(jLabel1))
                                        .addGap(234, 234, 234))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtIdAtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtFechaInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(btnInsertar))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCapacidadMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                            .addComponent(txtEdadMinima, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                            .addComponent(txtIdParque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtIdZona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(235, 235, 235))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btnBuscar)
                        .addGap(171, 171, 171)
                        .addComponent(btnCancelar)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtIdAtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtFechaInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRecargar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCancelar))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            int selZona = txtIdZona.getSelectedIndex();
            int selParque = txtIdParque.getSelectedIndex();
            
            if (selZona == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar una zona.");
                return;
            }
            if (selParque == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un parque.");
                return;
            }
            if(!txtIdAtraccion.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Recuerda que el ID de la atracción no se puede insertar.");
                return;
            }
            
            Atracciones a = new Atracciones();

            String nombre = txtNombre.getText().trim();
            String descripcion = txtDescripcion.getText().trim();
            String capacidadMaxima = txtCapacidadMaxima.getText().trim();
            String edadMinima = txtEdadMinima.getText().trim();
            String fechaInstalacion = txtFechaInstalacion.getText();
            Date fecha = validarFecha(fechaInstalacion);   

            if (nombre.isEmpty() || capacidadMaxima.isEmpty() || edadMinima.isEmpty() || fechaInstalacion.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }

            a.setNombre(nombre);            
            a.setFechaInstalacion(fecha);
            a.setDescripcion(descripcion);
            a.setCapacidadMaxima(Integer.parseInt(capacidadMaxima));
            a.setEdadMinima(Integer.parseInt(edadMinima));
            a.setCodZona(selZona);
            a.setCodParque(selParque);

            controller.create(a);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Atracción insertada correctamente.");
            limpiarCampos();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una atracción.");
            return;
        }

        try {            
            int selZona = txtIdZona.getSelectedIndex();
            int selParque = txtIdParque.getSelectedIndex();
            
            if (selZona == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar una zona.");
                return;
            }
            if (selParque == 0) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un parque.");
                return;
            }
            if(!txtIdAtraccion.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "Recuerda que el ID de la atracción no se puede actualizar.");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            Atracciones a = controller.findById(id);

            String nombre = txtNombre.getText().trim();
            String fechaInstalacion = txtFechaInstalacion.getText().trim();
            Date fecha = validarFecha(fechaInstalacion);
            String descripcion = txtDescripcion.getText().trim();
            String edadMinima = txtEdadMinima.getText().trim();
            String capacidadMaxima = txtCapacidadMaxima.getText().trim();

            // VALIDACIONES
            if (nombre.isEmpty() || edadMinima.isEmpty() 
                    || capacidadMaxima.isEmpty()
                    || fechaInstalacion.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            

            Integer edad = Integer.parseInt(edadMinima);
            int capacidadMax = Integer.parseInt(capacidadMaxima);

            if (edad < 0) {
                JOptionPane.showMessageDialog(this, "La edad mínima no puede ser negativa.");
                return;
            }

            if (capacidadMax <= 0) {
                JOptionPane.showMessageDialog(this, "La capacidad debe ser mayor que 0.");
                return;
            }

            // ACTUALIZAR DATOS
            a.setNombre(nombre);
            a.setDescripcion(descripcion);
            a.setEdadMinima(edad);
            a.setCapacidadMaxima(capacidadMax);
            a.setFechaInstalacion(fecha);
            a.setCodZona(selZona);
            a.setCodParque(selParque);

            controller.update(a);

            cargarTabla();

            JOptionPane.showMessageDialog(this,
                    "Atracción actualizada correctamente.");
            limpiarCampos();

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this,
                    "Los campos numéricos tienen un formato incorrecto.");

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una atracción.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar la atracción?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            controller.delete(id);

            cargarTabla();

            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Atracción eliminada");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar la atracción.\n" + "Tiene registros relacionados.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        cargarTabla();
        
        limpiarCampos();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            txtIdAtraccion.setText(jTable1.getValueAt(fila, 0).toString());
            txtNombre.setText(jTable1.getValueAt(fila, 1).toString());
            txtFechaInstalacion.setText(jTable1.getValueAt(fila, 2).toString());
            txtDescripcion.setText(jTable1.getValueAt(fila, 3).toString());
            txtCapacidadMaxima.setText(jTable1.getValueAt(fila, 4).toString());
            txtEdadMinima.setText(jTable1.getValueAt(fila, 5).toString());
            try {
                int idZonaVal = Integer.parseInt(jTable1.getValueAt(fila, 6).toString());
                txtIdZona.setSelectedIndex(idZonaVal);
            } catch (Exception ex) {
                txtIdZona.setSelectedIndex(0);
            }
            try {
                int idParqueVal = Integer.parseInt(jTable1.getValueAt(fila, 7).toString());
                txtIdParque.setSelectedIndex(idParqueVal);
            } catch (Exception ex) {
                txtIdParque.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        // LIMPIAR TABLA
        modelo.setRowCount(0);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        // CAMPOS FILTRO
        String idAtraccion = txtIdAtraccion.getText().trim();
        String nombre = txtNombre.getText().trim().toLowerCase();
        String fechaInstalacion = txtFechaInstalacion.getText().trim();
        String descripcion = txtDescripcion.getText().trim().toLowerCase();
        String edadMinima = txtEdadMinima.getText().trim();
        String capacidadMaxima = txtCapacidadMaxima.getText().trim();

        validarFecha(fechaInstalacion);
        
        int selZona = txtIdZona.getSelectedIndex();
        int selParque = txtIdParque.getSelectedIndex();

        List<Atracciones> lista = controller.findAll();

        boolean encontrado = false;

        for (Atracciones a : lista) {

            boolean coincide = true;

            // ID ATRACCION
            if (!idAtraccion.isEmpty()) {
                String id = String.valueOf(a.getCodAtraccion());

                if (!id.contains(idAtraccion)) {
                    coincide = false;
                }
            }

            // NOMBRE
            if (!nombre.isEmpty()) {

                String nombreAtraccion = "";

                if (a.getNombre() != null) {
                    nombreAtraccion = a.getNombre().toLowerCase();
                }

                if (!nombreAtraccion.contains(nombre)) {
                    coincide = false;
                }
            }

            // FECHA INSTALACION
            if (!fechaInstalacion.isEmpty()) {

                String fechaAtraccion = "";

                if (a.getFechaInstalacion() != null) {
                    fechaAtraccion = sdf.format(a.getFechaInstalacion()).toLowerCase();
                }

                if (!fechaAtraccion.contains(fechaInstalacion)) {
                    coincide = false;
                }
            }

            // DESCRIPCION
            if (!descripcion.isEmpty()) {

                String desc = "";

                if (a.getDescripcion() != null) {
                    desc = a.getDescripcion().toLowerCase();
                }

                if (!desc.contains(descripcion)) {
                    coincide = false;
                }
            }

            // EDAD MINIMA
            if (!edadMinima.isEmpty()) {

                String edad = String.valueOf(a.getEdadMinima());

                if (!edad.contains(edadMinima)) {
                    coincide = false;
                }
            }

            // CAPACIDAD MAXIMA
            if (!capacidadMaxima.isEmpty()) {

                String capacidad = String.valueOf(a.getCapacidadMaxima());

                if (!capacidad.contains(capacidadMaxima)) {
                    coincide = false;
                }
            }

            // FILTRO ZONA (combo)
            if (selZona != 0) {
                try {
                    if (a.getCodZona() != selZona) {
                        coincide = false;
                    }
                } catch (Exception ex) {
                    coincide = false;
                }
            }

            // FILTRO PARQUE (combo)
            if (selParque != 0) {
                try {
                    if (a.getCodParque() != selParque) {
                        coincide = false;
                    }
                } catch (Exception ex) {
                    coincide = false;
                }
            }

            // SI COINCIDE → AÑADIR FILA
            if (coincide) {

                modelo.addRow(new Object[]{
                    a.getCodAtraccion(),
                    a.getNombre(),
                    sdf.format(a.getFechaInstalacion()),
                    a.getDescripcion(),
                    a.getCapacidadMaxima(),
                    a.getEdadMinima(),
                    a.getCodZona(),
                    a.getCodParque()
                });

                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<Atracciones> lista = controller.findByCodParqueAndCodZona(idParque, idZona);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Atracciones a : lista) {

            modelo.addRow(new Object[]{
                a.getCodAtraccion(),
                a.getNombre(),
                sdf.format(a.getFechaInstalacion()),
                a.getDescripcion(),
                a.getCapacidadMaxima(),
                a.getEdadMinima(),
                a.getCodZona(),
                a.getCodParque()
            });
        }
    }

    private void limpiarCampos() {
        txtIdAtraccion.setText("");
        txtNombre.setText("");
        txtFechaInstalacion.setText("");
        txtDescripcion.setText("");
        txtCapacidadMaxima.setText("");
        txtEdadMinima.setText("");
        txtIdZona.setSelectedIndex(0);
        txtIdParque.setSelectedIndex(0);
        jTable1.clearSelection();
    }
    
    private Date validarFecha(String textoFecha) {

        try {

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);

            return sdf.parse(textoFecha);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fecha incorrecta.\nFormato requerido: dd/MM/yyyy\nEjemplo: 04/06/2026");
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogAtracciones dialog = new JDialogAtracciones(new javax.swing.JFrame(), true, 1, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCapacidadMaxima;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEdadMinima;
    private javax.swing.JTextField txtFechaInstalacion;
    private javax.swing.JTextField txtIdAtraccion;
    private javax.swing.JComboBox<String> txtIdParque;
    private javax.swing.JComboBox<String> txtIdZona;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
