/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Elena
 */
public class JDialogBackup extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogBackup.class.getName());
    private final String URL = "jdbc:mysql://127.0.0.1:3306/parqueatracciones?serverTimezone=UTC";
    private final String USER = "elena";
    private final String PASSWORD = "12a12b12c1";

    /**
     * Creates new form JDialogBackup
     */
    public JDialogBackup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Gestión Backups");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackup = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBackup.setFont(new java.awt.Font("David Libre", 3, 24)); // NOI18N
        btnBackup.setText("Crear Backup");
        btnBackup.addActionListener(this::btnBackupActionPerformed);

        btnRestaurar.setFont(new java.awt.Font("David Libre", 3, 24)); // NOI18N
        btnRestaurar.setText("Restaurar Último Backup");
        btnRestaurar.addActionListener(this::btnRestaurarActionPerformed);

        btnSalir.setFont(new java.awt.Font("David Libre", 3, 30)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnRestaurar)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(28, 28, 28))
        );

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Gestión de Copias de Seguridad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        try {

            crearBackup();

            JOptionPane.showMessageDialog(this, "Backup creado correctamente");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al crear backup:\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnBackupActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        try {

            restaurarUltimoBackup();

            guardarUltimoBackupRestaurado();
            JOptionPane.showMessageDialog(this, "Backup restaurado correctamente");

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Error al restaurar backup:\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void crearBackup() throws Exception {

        String fecha = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss").format(new Date());

        // MISMA carpeta para crear y restaurar
        Path carpetaBackup = Paths.get("backups", fecha);

        Files.createDirectories(carpetaBackup);

        List<String> tablas = Arrays.asList(
                "atracciones",
                "clientes",
                "detalleEmpleado",
                "detalleServicios",
                "empleados",
                "entradas",
                "oficinas",
                "parques",
                "servicios",
                "zonas"
        );

        Connection con = DriverManager.getConnection(URL, USER, PASSWORD);

        for (String tabla : tablas) {

            Statement st = con.createStatement();

            ResultSet rs = st.executeQuery("SELECT * FROM " + tabla);

            ResultSetMetaData meta = rs.getMetaData();

            int columnas = meta.getColumnCount();

            File archivo = carpetaBackup.resolve(tabla + ".csv").toFile();

            BufferedWriter bw = new BufferedWriter(new FileWriter(archivo));

            // CABECERAS
            for (int i = 1; i <= columnas; i++) {

                bw.write(meta.getColumnName(i));

                if (i < columnas) {
                    bw.write(";");
                }
            }

            bw.newLine();

            // DATOS
            while (rs.next()) {

                for (int i = 1; i <= columnas; i++) {

                    Object valor = rs.getObject(i);

                    // Evitar null y usar marcador exclusivo para restaurar correctamente
                    bw.write(valor != null ? valor.toString() : "__NULL__");

                    if (i < columnas) {
                        bw.write(";");
                    }
                }

                bw.newLine();
            }

            bw.close();
            rs.close();
            st.close();
        }

        con.close();
    }

    private String restaurarUltimoBackup() throws Exception {

        File carpetaBackups = new File("backups");

        File[] carpetas = carpetaBackups.listFiles(File::isDirectory);

        if (carpetas == null || carpetas.length == 0) {
            throw new Exception("No existen copias de seguridad");
        }

        File ultima = Arrays.stream(carpetas)
                .max(Comparator.comparingLong(File::lastModified))
                .orElseThrow();

        List<String> tablas = Arrays.asList(
                "atracciones",
                "clientes",
                "detalleEmpleado",
                "detalleServicios",
                "empleados",
                "entradas",
                "oficinas",
                "parques",
                "servicios",
                "zonas"
        );

        Connection con = null;
        Statement st = null;

        try {
            con = DriverManager.getConnection(URL, USER, PASSWORD);
            con.setAutoCommit(false);

            st = con.createStatement();

            // Desactivar claves foráneas
            st.execute("SET FOREIGN_KEY_CHECKS = 0");

            // Borrar tablas
            for (String tabla : tablas) {
                st.executeUpdate("DELETE FROM " + tabla);
            }

            // Restaurar datos
            for (String tabla : tablas) {

                File archivo = new File(ultima, tabla + ".csv");

                if (!archivo.exists()) {
                    continue;
                }

                List<String> lineas = Files.readAllLines(archivo.toPath());

                if (lineas.size() <= 1) {
                    continue;
                }

                String cabecera = lineas.get(0);

                String[] columnas = cabecera.split(";");

                String placeholders = String.join(",",
                        java.util.Collections.nCopies(columnas.length, "?"));

                String sql = "INSERT INTO " + tabla
                        + " VALUES (" + placeholders + ")";

                PreparedStatement ps = con.prepareStatement(sql);

                for (int i = 1; i < lineas.size(); i++) {

                    String[] valores = lineas.get(i).split(";", -1);

                    for (int j = 0; j < valores.length; j++) {
                        String valor = valores[j];
                        if ("__NULL__".equals(valor) || valor.isEmpty()) {
                            ps.setNull(j + 1, java.sql.Types.NULL);
                        } else {
                            ps.setString(j + 1, valor);
                        }
                    }

                    ps.executeUpdate();
                }

                ps.close();
            }

            // Reactivar claves foráneas
            st.execute("SET FOREIGN_KEY_CHECKS = 1");
            con.commit();

        } catch (Exception ex) {
            if (con != null) {
                try {
                    con.rollback();
                } catch (Exception rollbackEx) {
                    logger.log(java.util.logging.Level.SEVERE, "Error al revertir restauración", rollbackEx);
                }
            }
            throw ex;
        } finally {
            if (st != null) {
                try {
                    st.execute("SET FOREIGN_KEY_CHECKS = 1");
                } catch (Exception ignore) {
                }
                try {
                    st.close();
                } catch (Exception ignore) {
                }
            }
            if (con != null) {
                try {
                    con.setAutoCommit(true);
                } catch (Exception ignore) {
                }
                try {
                    con.close();
                } catch (Exception ignore) {
                }
            }
        }
        
        return ultima.getName();
    }

    private void guardarUltimoBackupRestaurado() throws Exception {

        String nombreBackup = restaurarUltimoBackup();

        try (FileWriter fw = new FileWriter("backups/ultimoBackupRestaurado.txt")) {
            fw.write("Última copia restaurada: " + nombreBackup);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { // implicitly declared classes are not supported in -source 21 (use -source 25 or higher to enable implicitly declared classes)
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogBackup dialog = new JDialogBackup(new javax.swing.JFrame(), true); // non-static variable this cannot be referenced from a static context
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
