/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.controladores.OficinasController;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.modelos.entidades.Oficinas;

/**
 *
 * @author Elena
 */
public class JDialogOficinas extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogOficinas.class.getName());
    private OficinasController controller;
    private String regexTelefono = "^[6789][0-9]{8}$";

    /**
     * Creates new form JDialogOficinas
     */
    public JDialogOficinas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Gestión Oficinas");
        this.setSize(925, 600);
        this.setResizable(false);
        setLocationRelativeTo(null);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("parqueAtracciones");
        this.controller = new OficinasController(emf);

        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdOficina1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdOficina = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtIdParque = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Gestión Oficinas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Dirección", "Teléfono", "ID Parque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel2.setText("Dirección:");

        jLabel3.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel3.setText("ID Oficina:");

        jLabel4.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel4.setText("Teléfono:");

        jLabel5.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel5.setText("Parque:");

        btnInsertar.setFont(new java.awt.Font("David Libre", 1, 12)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("David Libre", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("David Libre", 1, 12)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("David Libre", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnRecargar.setFont(new java.awt.Font("David Libre", 1, 12)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("David Libre", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnBuscar.setFont(new java.awt.Font("David Libre", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtIdParque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona Parque --", "Parque Aventura", "Diversion Park", "Magic World", "FunLand", "AquaPark" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addGap(408, 408, 408))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBorrar)
                                .addGap(147, 147, 147)
                                .addComponent(btnLimpiar)
                                .addGap(163, 163, 163)
                                .addComponent(btnRecargar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(txtIdOficina))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(txtIdParque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(167, 167, 167)))
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(161, 161, 161)
                .addComponent(btnCancelar)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(btnBorrar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnRecargar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnBuscar))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        cargarTabla();

        limpiarCampos();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una oficina.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar la oficina?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            controller.delete(id);

            cargarTabla();

            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Oficina eliminada");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar la oficina.\n" + "Tiene registros relacionados.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            txtIdOficina.setText(jTable1.getValueAt(fila, 0).toString());
            txtDireccion.setText(jTable1.getValueAt(fila, 1).toString());
            txtTelefono.setText(jTable1.getValueAt(fila, 2).toString());
            try {
                int idParqueVal = Integer.parseInt(jTable1.getValueAt(fila, 3).toString());
                txtIdParque.setSelectedIndex(idParqueVal);
            } catch (Exception ex) {
                txtIdParque.setSelectedIndex(0);
            }

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una oficina.");
            return;
        }

        try {

            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            Oficinas o = controller.findById(id);

            String direccion = txtDireccion.getText().trim();
            String telefono = txtTelefono.getText().trim();

            int selParque = txtIdParque.getSelectedIndex();

            if (selParque != o.getCodParque()) {
                JOptionPane.showMessageDialog(this, "No se puede reasignar una oficina.\n Elimina esta oficina y crea una nueva para cambiar el parque.");
                return;
            }
            if (direccion.isEmpty() || telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            if (!txtIdOficina.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID de la oficina no se puede actualizar.");
                return;
            }
            if (!telefono.matches(regexTelefono)) {
                JOptionPane.showMessageDialog(this, "El teléfono debe de tener 9 números.");
                return;
            }

            o.setDireccion(direccion);
            o.setTelefono(telefono);

            controller.update(o);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Oficia actualizada correctamente.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        String idTexto = txtIdOficina.getText().trim();
        String direccion = txtDireccion.getText().trim().toLowerCase();
        String telefono = txtTelefono.getText().trim().toLowerCase();
        int selParque = txtIdParque.getSelectedIndex();
        String codParque = selParque > 0 ? String.valueOf(selParque) : "";

        List<Oficinas> lista = controller.findAll();

        boolean encontrado = false;

        for (Oficinas o : lista) {

            boolean coincide = true;

            if (!idTexto.isEmpty()) {

                String idOficina = String.valueOf(o.getCodOficina());

                if (!idOficina.contains(idTexto)) {
                    coincide = false;
                }
            }

            if (!direccion.isEmpty()
                    && !o.getDireccion().toLowerCase().contains(direccion)) {

                coincide = false;
            }

            if (!telefono.isEmpty()
                    && !o.getTelefono().toLowerCase().contains(telefono)) {

                coincide = false;
            }

            if (!codParque.isEmpty()) {

                String parque = String.valueOf(o.getCodParque());

                if (!parque.contains(codParque)) {
                    coincide = false;
                }
            }

            if (coincide) {

                modelo.addRow(new Object[]{
                    o.getCodOficina(),
                    o.getDireccion(),
                    o.getTelefono(),
                    o.getCodParque()
                });

                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            Oficinas o = new Oficinas();
            String direccion = txtDireccion.getText().trim();
            String telefono = txtTelefono.getText().trim();

            int selParque = txtIdParque.getSelectedIndex();

            if (controller.existeOficinaParaParque(selParque)) {
                JOptionPane.showMessageDialog(this, "Ya existe una oficina asociada a este parque.");
                return;
            }
            if (direccion.isEmpty() || telefono.isEmpty() || selParque == 0) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            if (!txtIdOficina.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID de la oficina no se puede insertar.");
                return;
            }
            if (!telefono.matches(regexTelefono)) {
                JOptionPane.showMessageDialog(this, "El teléfono debe de tener 9 números.");
                return;
            }

            o.setDireccion(direccion);
            o.setTelefono(telefono);
            o.setCodParque(selParque);

            controller.create(o);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Oficina insertada correctamente.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<Oficinas> lista = controller.findAll();

        for (Oficinas o : lista) {

            modelo.addRow(new Object[]{
                o.getCodOficina(),
                o.getDireccion(),
                o.getTelefono(),
                o.getCodParque()
            });
        }
    }

    private void limpiarCampos() {
        txtIdOficina.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtIdParque.setSelectedIndex(0);
        jTable1.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogOficinas dialog = new JDialogOficinas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdOficina;
    private javax.swing.JTextField txtIdOficina1;
    private javax.swing.JComboBox<String> txtIdParque;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
