/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.controladores.ClientesController;
import models.modelos.entidades.Clientes;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import javax.swing.table.DefaultTableModel;

import java.util.List;
import javax.swing.JOptionPane;

import java.text.SimpleDateFormat;
import java.util.Calendar;

import java.util.Date;

/**
 *
 * @author Elena
 */
public class JDialogClientes extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogClientes.class.getName());
    private ClientesController controller;

    /**
     * Creates new form JDialogClientes
     */
    public JDialogClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Gestión Clientes");
        this.setSize(925, 600);
        this.setResizable(false);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("parqueAtracciones");
        this.controller = new ClientesController(emf);

        cargarTabla();

    }

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<Clientes> lista = controller.findAll();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Clientes c : lista) {
            modelo.addRow(new Object[]{
                c.getCodCliente(),
                c.getNombre(),
                c.getApe1cli(),
                c.getApe2cli(),
                c.getDni(),
                sdf.format(c.getFechaNacimiento()),
                c.getEmail(),
                c.getTelefono(),
                c.getCodResponsable()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodResponsable1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnInsertar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApe1 = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtApe2 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFecNac = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtCodResponsable = new javax.swing.JComboBox<>();

        txtCodResponsable1.addActionListener(this::txtCodResponsable1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido 1", "Apellido 2", "DNI", "Fecha Nacimiento", "Email", "Teléfono", "Cód. Responsable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Clientes");

        btnInsertar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnRecargar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnCerrar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        jLabel2.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel3.setText("Apellido 1:");

        jLabel4.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel4.setText("Apellido 2:");

        jLabel5.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel5.setText("DNI:");

        jLabel6.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento:");

        jLabel8.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel9.setText("Responsable: ");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtApe1.addActionListener(this::txtApe1ActionPerformed);

        jLabel10.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabel10.setText("ID Cliente:");

        btnBuscar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtCodResponsable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecciona cliente --", "Juan Perez Lopez", "Ana Gomez Ruiz", "Luis Diaz Soto", "Maria Lopez Gil", "Carlos Navarro Rey" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApe1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApe2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 73, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)))))
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFecNac, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(txtIdCliente)
                    .addComponent(txtCodResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(297, 297, 297))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(409, 409, 409))))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(btnInsertar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtApe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(254, 254, 254))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            Clientes c = new Clientes();

            String nombre = txtNombre.getText();
            String ape1 = txtApe1.getText();
            String ape2 = txtApe2.getText();
            String dni = txtDni.getText();
            String telefono = txtTelefono.getText();
            String email = txtEmail.getText();
            String fechaNacimiento = txtFecNac.getText();

            // FECHA
            Date fecha = validarFecha(fechaNacimiento);

            if (fecha == null) {
                return;
            }

            if (!txtIdCliente.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID del cliente no se puede insertar.");
                return;
            }

            // CALCULAR EDAD
            java.util.Calendar hoy = java.util.Calendar.getInstance();
            java.util.Calendar nacimiento = java.util.Calendar.getInstance();
            nacimiento.setTime(fecha);

            int edad = hoy.get(java.util.Calendar.YEAR) - nacimiento.get(java.util.Calendar.YEAR);

            // SI ES MENOR → responsable obligatorio
            if (edad < 18) {
                int selResponsable = txtCodResponsable.getSelectedIndex();
                if (selResponsable == 0) {
                    JOptionPane.showMessageDialog(this, "Los menores necesitan responsable. Debes seleccionar uno.");
                    return;
                }

                Integer idResponsable = selResponsable;

                // BUSCAR RESPONSABLE
                Clientes responsable = controller.findById(idResponsable);

                // COMPROBAR QUE EXISTE
                if (responsable == null) {
                    JOptionPane.showMessageDialog(this, "El responsable no existe.");
                    return;
                }

                // CALCULAR EDAD DEL RESPONSABLE
                Calendar hoyResponsable = Calendar.getInstance();

                Calendar nacimientoResponsable = Calendar.getInstance();

                nacimientoResponsable.setTime(responsable.getFechaNacimiento());

                int edadResponsable = hoyResponsable.get(Calendar.YEAR) - nacimientoResponsable.get(Calendar.YEAR);

                // SI EL RESPONSABLE ES MENOR
                if (edadResponsable < 18) {
                    JOptionPane.showMessageDialog(this, "El responsable debe ser mayor de edad.");
                    return;
                }

                c.setCodResponsable(idResponsable);

            } else {
                c.setCodResponsable(null);
            }

            if (!validarDatos(dni, telefono, email)) {
                return;
            }

            if (!nombre.isEmpty() && !ape1.isEmpty() && !dni.isEmpty() && !telefono.isEmpty() && !email.isEmpty() && !fechaNacimiento.isEmpty()) {
                c.setNombre(nombre);
                c.setApe1cli(ape1);
                c.setApe2cli(ape2);
                c.setDni(dni);
                c.setTelefono(telefono);
                c.setEmail(email);
                c.setFechaNacimiento(fecha);
            } else {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios que no pueden estar vacíos.");
                return;
            }

            controller.create(c);

            JOptionPane.showMessageDialog(this, "Cliente insertado correctamente.");
            cargarTabla();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente");
            return;
        }
        if (!txtIdCliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Recuerda que el ID del cliente no se puede actualizar.");
            return;
        }

        try {

            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            Clientes c = controller.findById(id);

            String nombre = txtNombre.getText().trim();
            String ape1 = txtApe1.getText().trim();
            String ape2 = txtApe2.getText().trim();
            String dni = txtDni.getText().trim();
            String telefono = txtTelefono.getText().trim();
            String email = txtEmail.getText().trim();

            // VALIDAR CAMPOS OBLIGATORIOS
            if (nombre.isEmpty() || ape1.isEmpty() || dni.isEmpty() || telefono.isEmpty() || email.isEmpty()
                    || txtFecNac.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }

            if (!validarDatos(dni, telefono, email)) {
                return;
            }

            // FECHA
            Date fecha = validarFecha(txtFecNac.getText());

            if (fecha == null) {
                return;
            }

            // CALCULAR EDAD
            java.util.Calendar hoy = java.util.Calendar.getInstance();
            java.util.Calendar nacimiento = java.util.Calendar.getInstance();

            nacimiento.setTime(fecha);

            int edad = hoy.get(java.util.Calendar.YEAR) - nacimiento.get(java.util.Calendar.YEAR);

            // RESPONSABLE
            if (edad < 18) {
                int selResponsable = txtCodResponsable.getSelectedIndex();
                if (selResponsable == 0) {
                    JOptionPane.showMessageDialog(this, "Los menores necesitan responsable. Debes seleccionar uno.");
                    return;
                }

                Integer idResponsable = selResponsable;

                // BUSCAR RESPONSABLE
                Clientes responsable = controller.findById(idResponsable);

                // COMPROBAR QUE EXISTE
                if (responsable == null) {
                    JOptionPane.showMessageDialog(this, "El responsable no existe.");
                    return;
                }

                // CALCULAR EDAD DEL RESPONSABLE
                Calendar hoyResponsable = Calendar.getInstance();

                Calendar nacimientoResponsable = Calendar.getInstance();

                nacimientoResponsable.setTime(responsable.getFechaNacimiento());

                int edadResponsable = hoyResponsable.get(Calendar.YEAR) - nacimientoResponsable.get(Calendar.YEAR);

                // SI EL RESPONSABLE ES MENOR
                if (edadResponsable < 18) {
                    JOptionPane.showMessageDialog(this, "El responsable debe ser mayor de edad.");
                    return;
                }

                c.setCodResponsable(idResponsable);

            } else {
                c.setCodResponsable(null);
            }

            // ACTUALIZAR DATOS
            c.setNombre(nombre);
            c.setApe1cli(ape1);
            c.setApe2cli(ape2);
            c.setDni(dni);
            c.setTelefono(telefono);
            c.setEmail(email);
            c.setFechaNacimiento(fecha);

            controller.update(c);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Cliente actualizado correctamente");

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el cliente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            controller.delete(id);

            cargarTabla();

            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Cliente eliminado");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar el cliente.\n" + "Tiene registros relacionados.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        cargarTabla();

        limpiarCampos();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtApe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApe1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila != -1) {
            txtIdCliente.setText(jTable1.getValueAt(fila, 0).toString());
            txtNombre.setText(jTable1.getValueAt(fila, 1).toString());
            txtApe1.setText(jTable1.getValueAt(fila, 2).toString());
            txtApe2.setText(jTable1.getValueAt(fila, 3).toString());
            txtDni.setText(jTable1.getValueAt(fila, 4).toString());
            txtFecNac.setText(jTable1.getValueAt(fila, 5).toString());
            txtEmail.setText(jTable1.getValueAt(fila, 6).toString());
            txtTelefono.setText(jTable1.getValueAt(fila, 7).toString());
            Object responsable = jTable1.getValueAt(fila, 8);

            if (responsable != null) {
                try {
                    int idResponsableVal = Integer.parseInt(responsable.toString());
                    txtCodResponsable.setSelectedIndex(idResponsableVal);
                } catch (Exception ex) {
                    txtCodResponsable.setSelectedIndex(0);
                }
            } else {
                txtCodResponsable.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtCodResponsable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodResponsable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodResponsable1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        // LIMPIAR TABLA
        modelo.setRowCount(0);

        // CAMPOS FILTRO
        String idTexto = txtIdCliente.getText().trim();
        String nombre = txtNombre.getText().trim().toLowerCase();
        String ape1 = txtApe1.getText().trim().toLowerCase();
        String ape2 = txtApe2.getText().trim().toLowerCase();
        String dni = txtDni.getText().trim().toLowerCase();
        String email = txtEmail.getText().trim().toLowerCase();
        String telefono = txtTelefono.getText().trim().toLowerCase();
        String fecha = txtFecNac.getText().trim();
        int selResponsable = txtCodResponsable.getSelectedIndex();

        List<Clientes> lista = controller.findAll();

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        validarFecha(fecha);

        boolean encontrado = false;

        for (Clientes c : lista) {

            boolean coincide = true;

            // ID
            if (!idTexto.isEmpty()) {

                String idCliente = String.valueOf(c.getCodCliente());

                if (!idCliente.contains(idTexto)) {
                    coincide = false;
                }
            }

            // NOMBRE
            if (!nombre.isEmpty() && !c.getNombre().toLowerCase().contains(nombre)) {
                coincide = false;
            }

            // APELLIDO 1
            if (!ape1.isEmpty() && !c.getApe1cli().toLowerCase().contains(ape1)) {
                coincide = false;
            }

            // APELLIDO 2
            if (!ape2.isEmpty()) {

                String ape2cli = "";

                if (c.getApe2cli() != null) {
                    ape2cli = c.getApe2cli().toLowerCase();
                }

                if (!ape2cli.contains(ape2)) {
                    coincide = false;
                }
            }

            // DNI
            if (!dni.isEmpty() && !c.getDni().toLowerCase().contains(dni)) {
                coincide = false;
            }

            // EMAIL
            if (!email.isEmpty() && !c.getEmail().toLowerCase().contains(email)) {
                coincide = false;
            }

            // TELEFONO
            if (!telefono.isEmpty() && !c.getTelefono().toLowerCase().contains(telefono)) {
                coincide = false;
            }

            // FECHA: aceptar formato dd/MM/yyyy
            if (!fecha.isEmpty()) {
                boolean matchFecha = false;

                try {
                    java.util.Date fechaBuscada = sdf.parse(fecha);
                    String buscadaFormateada = sdf.format(fechaBuscada);
                    String fechaCliente = sdf.format(c.getFechaNacimiento());

                    if (fechaCliente.equals(buscadaFormateada)) {
                        matchFecha = true;
                    }
                } catch (Exception ex) {
                    // Si no se puede parsear, hacer búsqueda por contains sobre la cadena formateada
                    String fechaCliente = sdf.format(c.getFechaNacimiento()).toLowerCase();

                    if (fechaCliente.contains(fecha.toLowerCase())) {
                        matchFecha = true;
                    }
                }

                if (!matchFecha) {
                    coincide = false;
                }
            }

            // ID RESPONSABLE: aplicar filtro solo si se ha seleccionado uno
            if (selResponsable != 0) {
                String respCliente = "";

                if (c.getCodResponsable() != null) {
                    respCliente = String.valueOf(c.getCodResponsable());
                }

                if (!respCliente.contains(String.valueOf(selResponsable))) {
                    coincide = false;
                }
            }

            // SI COINCIDE → AÑADIR A TABLA
            if (coincide) {
                modelo.addRow(new Object[]{
                    c.getCodCliente(),
                    c.getNombre(),
                    c.getApe1cli(),
                    c.getApe2cli(),
                    c.getDni(),
                    sdf.format(c.getFechaNacimiento()),
                    c.getEmail(),
                    c.getTelefono(),
                    c.getCodResponsable()
                });

                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void limpiarCampos() {
        txtNombre.setText("");
        txtApe1.setText("");
        txtApe2.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        txtEmail.setText("");
        txtFecNac.setText("");
        txtCodResponsable.setSelectedIndex(0);
        txtIdCliente.setText("");

        jTable1.clearSelection();
    }

    private Date validarFecha(String textoFecha) {

        try {

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);

            return sdf.parse(textoFecha);

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Fecha incorrecta.\nFormato requerido: dd/MM/yyyy\nEjemplo: 04/06/2026", "Error de fecha", JOptionPane.ERROR_MESSAGE);

            return null;
        }
    }

    private boolean validarDatos(String dni, String telefono, String correo) {
        String regexDNI = "^[0-9]{8}[A-Za-z]$";
        String regexTelefono = "^[6789][0-9]{8}$";
        String regexEmail = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";

        if (!dni.matches(regexDNI)) {
            JOptionPane.showMessageDialog(this, "DNI incorrecto. Formato: 12345678Z");
            return false;
        }

        if (!telefono.matches(regexTelefono)) {
            JOptionPane.showMessageDialog(this, "Teléfono incorrecto. Debe tener 9 cifras.");
            return false;
        }

        if (!correo.matches(regexEmail)) {
            JOptionPane.showMessageDialog(this, "Correo electrónico incorrecto.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogClientes dialog = new JDialogClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApe1;
    private javax.swing.JTextField txtApe2;
    private javax.swing.JComboBox<String> txtCodResponsable;
    private javax.swing.JTextField txtCodResponsable1;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecNac;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
