/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controllers.controladores.ParquesController;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.modelos.entidades.Parques;

/**
 *
 * @author Elena
 */
public class JDialogParques extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogParques.class.getName());
    private ParquesController controller;

    /**
     * Creates new form JDialogParques
     */
    public JDialogParques(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Gestión Parques");
        this.setSize(925, 600);
        this.setResizable(false);
        setLocationRelativeTo(null);

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("parqueAtracciones");

        controller = new ParquesController(emf);

        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelNombre2 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCapacidadMaxima = new javax.swing.JTextField();
        txtMetrosCuadrados = new javax.swing.JTextField();
        jLabelNombre3 = new javax.swing.JLabel();
        txtIdParque = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("David Libre", 1, 36)); // NOI18N
        jLabel1.setText("Parques");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Dirección", "Ciudad", "M²", "Capacidad. Máx"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnCerrar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);

        btnActualizar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnBorrar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnRecargar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(this::btnRecargarActionPerformed);

        btnInsertar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(this::btnInsertarActionPerformed);

        jLabelDireccion.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabelDireccion.setText("Dirección:");

        jLabelCiudad.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabelCiudad.setText("Ciudad:");

        jLabelNombre.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelNombre1.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabelNombre1.setText("Metros cuadrados:");

        jLabelNombre2.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabelNombre2.setText("Capacidad Máxima:");

        txtCiudad.addActionListener(this::txtCiudadActionPerformed);

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtDireccion.addActionListener(this::txtDireccionActionPerformed);

        txtCapacidadMaxima.addActionListener(this::txtCapacidadMaximaActionPerformed);

        txtMetrosCuadrados.addActionListener(this::txtMetrosCuadradosActionPerformed);

        jLabelNombre3.setFont(new java.awt.Font("David Libre", 3, 14)); // NOI18N
        jLabelNombre3.setText("ID  Parque:");

        txtIdParque.addActionListener(this::txtIdParqueActionPerformed);

        btnBuscar.setFont(new java.awt.Font("David Libre", 1, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnActualizar)
                        .addGap(120, 120, 120)
                        .addComponent(btnBorrar)
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRecargar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelNombre2)
                                    .addComponent(jLabelNombre1)
                                    .addComponent(jLabelNombre3))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCapacidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMetrosCuadrados, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdParque, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(417, 417, 417)
                                .addComponent(btnInsertar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(378, 378, 378))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(70, 70, 70)
                        .addComponent(btnCerrar)
                        .addGap(322, 322, 322))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsertar)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMetrosCuadrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCiudad)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre3)
                    .addComponent(txtIdParque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnBorrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRecargar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnBuscar))
                .addGap(167, 167, 167))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Selecciona un parque.");
            return;
        }

        try {

            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            Parques p = controller.findById(id);
            
            String nombre = txtNombre.getText().trim();
            String direccion = txtDireccion.getText().trim();
            String ciudad = txtCiudad.getText().trim();
            String metrosCuadrados = txtMetrosCuadrados.getText().trim();
            String capacidadMaxima = txtCapacidadMaxima.getText().trim();

            if (nombre.isEmpty() || direccion.isEmpty() || ciudad.isEmpty()
                    || metrosCuadrados.isEmpty()|| capacidadMaxima.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            if (!txtIdParque.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID del parque no se puede actualizar.");
                return;
            }  
            

            p.setNombre(nombre);
            p.setDireccion(direccion);
            p.setCiudad(ciudad);
            p.setMetrosCuadrados(Long.parseLong(metrosCuadrados));
            p.setCapacidadMaxima(Long.parseLong(capacidadMaxima));

            controller.update(p);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Parque actualizado correctamente.");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un parque.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar el parque?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Integer id = (Integer) jTable1.getValueAt(fila, 0);

            controller.delete(id);

            cargarTabla();

            limpiarCampos();

            JOptionPane.showMessageDialog(this, "Parque eliminado");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar el parque.\n" + "Tiene registros relacionados.");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila != -1 && evt.getClickCount() != 2) {
            txtIdParque.setText(jTable1.getValueAt(fila, 0).toString());
            txtNombre.setText(jTable1.getValueAt(fila, 1).toString());
            txtDireccion.setText(jTable1.getValueAt(fila, 2).toString());
            txtCiudad.setText(jTable1.getValueAt(fila, 3).toString());
            txtMetrosCuadrados.setText(jTable1.getValueAt(fila, 4).toString());
            txtCapacidadMaxima.setText(jTable1.getValueAt(fila, 5).toString());
        }

        if (fila != -1 && evt.getClickCount() == 2) {
            Integer idParque = (Integer) jTable1.getValueAt(fila, 0);

            JDialogZonas dialog = new JDialogZonas(null, true, idParque);

            dialog.setVisible(true);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCapacidadMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadMaximaActionPerformed

    private void txtMetrosCuadradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMetrosCuadradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMetrosCuadradosActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            Parques p = new Parques();

            String nombre = txtNombre.getText().trim();
            String direccion = txtDireccion.getText().trim();
            String ciudad = txtCiudad.getText().trim();
            String metrosCuadrados = txtMetrosCuadrados.getText().trim();
            String capacidadMaxima = txtCapacidadMaxima.getText().trim();

            if (nombre.isEmpty() || direccion.isEmpty() || ciudad.isEmpty()
                    || metrosCuadrados.isEmpty()|| capacidadMaxima.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Hay campos obligatorios vacíos.");
                return;
            }
            if (!txtIdParque.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Recuerda que el ID del parque no se puede insertar.");
                return;
            }  

            p.setNombre(nombre);
            p.setDireccion(direccion);
            p.setCiudad(ciudad);
            p.setMetrosCuadrados(Long.parseLong(metrosCuadrados));
            p.setCapacidadMaxima(Long.parseLong(capacidadMaxima));

            controller.create(p);

            cargarTabla();

            JOptionPane.showMessageDialog(this, "Parque insertado correctamente.");
            cargarTabla();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        cargarTabla();
        
        limpiarCampos();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtIdParqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdParqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdParqueActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        String idTexto = txtIdParque.getText().trim();
        String nombre = txtNombre.getText().trim().toLowerCase();
        String ciudad = txtCiudad.getText().trim().toLowerCase();
        String direccion = txtDireccion.getText().trim().toLowerCase();

        List<Parques> lista = controller.findAll();

        boolean encontrado = false;

        for (Parques p : lista) {

            boolean coincide = true;

            if (!idTexto.isEmpty()) {
                String idParque = String.valueOf(p.getCodParque());

                if (!idParque.contains(idTexto)) {
                    coincide = false;
                }
            }

            if (!nombre.isEmpty() && !p.getNombre().toLowerCase().contains(nombre)) {
                coincide = false;
            }

            if (!ciudad.isEmpty() && !p.getCiudad().toLowerCase().contains(ciudad)) {
                coincide = false;
            }

            if (!direccion.isEmpty() && !p.getDireccion().toLowerCase().contains(direccion)) {
                coincide = false;
            }

            if (coincide) {
                modelo.addRow(new Object[]{
                    p.getCodParque(),
                    p.getNombre(),
                    p.getCiudad(),
                    p.getDireccion(),
                    p.getMetrosCuadrados(),
                    p.getCapacidadMaxima()
                     
                });

                encontrado = true;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        List<Parques> lista = controller.findAll();

        for (Parques p : lista) {

            modelo.addRow(new Object[]{
                p.getCodParque(),
                p.getNombre(),
                p.getDireccion(),
                p.getCiudad(),
                p.getMetrosCuadrados(),
                p.getCapacidadMaxima()
            });
        }
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtCiudad.setText("");
        txtDireccion.setText("");
        txtMetrosCuadrados.setText("");
        txtCapacidadMaxima.setText("");
        txtIdParque.setText("");
        jTable1.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogParques dialog = new JDialogParques(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCapacidadMaxima;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdParque;
    private javax.swing.JTextField txtMetrosCuadrados;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
