package vistas;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import modelos.ListaPlatos;
import modelos.ModeloTablaPlato;
import modelos.Plato;

public class Principal extends javax.swing.JFrame {

    // Lista de platos que se carga desde el fichero restaurante.csv
    private final ListaPlatos listaPlatos;

    public Principal() {
        listaPlatos = new ListaPlatos();
        initComponents();
        cargarDatosJTable();
    }

    // Este método inserta los datos de la lista en el jtable
    private void cargarDatosJTable() {

        ModeloTablaPlato modelo = new ModeloTablaPlato();
        int numColumnas = modelo.getColumnCount();
        Object[] fila = new Object[numColumnas];

        for (Plato plato : listaPlatos.getLista()) {
            fila[0] = plato.getIdPlato();
            fila[1] = plato.getNombre();
            fila[2] = plato.getDescripcion();
            fila[3] = plato.getPrecio();
            modelo.addRow(fila);
        }

        jTable1.setModel(modelo);
    }

    // Método para obtener la lista de platos cargada en el formulario
    // desde el diálogo
    public ListaPlatos getListaPlatos() {
        return this.listaPlatos;
    }

    // Método para obtener el jtable del formulario
    // desde el diálogo
    public JTable getJTable() {
        return this.jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BotonEditar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Platos");
        setBounds(new java.awt.Rectangle(150, 150, 0, 0));

        jScrollPane1.setViewportView(jTable1);

        BotonEditar.setText("Editar");
        BotonEditar.addActionListener((evt) -> {
            BotonEditarActionPerformed(evt);
        });

        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener((evt) -> {
            BotonActualizarActionPerformed(evt);
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener((evt) -> {
            BotonSalirActionPerformed(evt);
        });

        jLabel1.setText("Platos con precio mayor a 10 € (máx. 15)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonSalir)
                    .addComponent(BotonActualizar)
                    .addComponent(BotonEditar))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(BotonSalir)
                        .addGap(70, 70, 70)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // Antes de nada comprobar que se ha selccionado algo
        if (jTable1.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "No has seleccionado ningún registro");
        } else {
            // Muestro la ventana de edición
            // Este diálogo depende de la ventana principal
            // y por tanto se le pasa como parámetro (this)
            // y se le indica que es modal (true)
            // Esto significa que el usuario no podrá interactuar con la ventana
            // principal hasta que cierre el diálogo
            new Editar(this, true).setVisible(true);
            // Una vez termine la ejecución de la ventana Editar
            // Llamo a cargar de nuevo los datos en el jTable con los cambios
            cargarDatosJTable();
        }
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String idPlato = (String) modelo.getValueAt(i, 0);
            Object precioValue = modelo.getValueAt(i, 3);
            double precio = 0.0;
            if (precioValue instanceof Number) {
                precio = ((Number) precioValue).doubleValue();
            } else if (precioValue instanceof String) {
                try {
                    precio = Double.parseDouble((String) precioValue);
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Precio no válido en la fila " + (i + 1));
                    return;
                }
            }
            listaPlatos.getPlato(idPlato).setPrecio(precio);
        }
        listaPlatos.getLista().forEach(System.out::println);
        JOptionPane.showMessageDialog(this, "Precios actualizados correctamente.");
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
